admin_module_catalog_refresh:
    path:     /catalog/refresh/{category}/{keyword}
    methods:  [GET]
    defaults:
        category:
        keyword:
        _controller: prestashop.core.api.improve.module.controller:refreshCatalogAction
        _legacy_controller: 'ADMINMODULESSF'

admin_module_configure_action:
    path:     /manage/action/configure/{module_name}
    methods:  [GET, POST]
    defaults:
        _controller: prestashop.core.api.improve.module.controller:configureModuleAction
        _legacy_controller: AdminModules

admin_module_manage_action_bulk:
    path:     /manage/bulk/{action}
    methods:  [POST]
    defaults:
        _controller: prestashop.core.api.improve.module.controller:moduleAction
    requirements:
        action: install|uninstall|configure|enable|disable|reset|upgrade

admin_module_manage_update_all:
    path:     /manage/update/all
    methods:  [POST]
    defaults:
        _controller: prestashop.core.api.improve.module.controller:moduleAction

admin_module_import:
    path:     /import
    methods:  [POST]
    defaults:
        module_name:
        _controller: prestashop.core.api.improve.module.controller:importModuleAction

admin_module_notification_count:
    path:     /notifications/count
    methods:  [GET]
    defaults:
        _controller: prestashop.core.api.improve.module.controller:notificationsCountAction
        _legacy_controller: AdminModulesNotifications
